# To run: docker-compose up

version: '3.8'

services:
  api:
    build: .

    container_name: cloud-ai-router

    ports:
      - "8000:8000"

    environment:
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    volumes:
      - ./app:/app/app

    restart: unless-stopped

    tty: true
    stdin_open: true
